name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
             java-version: '11' # Change this to your desired Java version
             distribution: 'adopt' # Add this line to specify the distribution

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: |
          docker build -t your-docker-image-name:latest .
          docker tag your-docker-image-name:latest your-docker-repo/your-docker-image-name:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-docker-repo/your-docker-image-name:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



